// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

// Test verification with incorrect proof

const Verifier = artifacts.require("Verifier");
const proofJson = require("./proof.json");
const { proof, inputs } = proofJson;

contract("Verifier", async () => {
  it("Test verification with correct proof", async () => {
    const contract = await Verifier.new();
    const verificationResult = await contract.verifyTx(proof, inputs);
    assert.equal(verificationResult, true);
  });

  it("Test verification with incorrect proof", async () => {
    const contract = await Verifier.new();
    const verificationResult = await contract.verifyTx(
      proof,
      [...inputs].reverse()
    );
    assert.equal(verificationResult, false);
  });
});
